arrowParens = "always"
bracketSpacing = true
insertPragma = false
jsxBracketSameLine = false
printWidth = 80
proseWrap = "always"
requirePragma = false
semi = true
singleQuote = false
tabWidth = 2
trailingComma = "all"

[[overrides]]
files = "*.md"
[overrides.options]
proseWrap = "never"
